<?php

namespace App\Enumerations;


enum EnumTimezones: int
{

    case TMZ_000_AFRICA_ABIDJAN = 0;
    case TMZ_001_AFRICA_ACCRA = 1;
    case TMZ_002_AFRICA_ADDIS_ABABA = 2;
    case TMZ_003_AFRICA_ALGIERS = 3;
    case TMZ_004_AFRICA_ASMARA = 4;
    case TMZ_005_AFRICA_ASMERA = 5;
    case TMZ_006_AFRICA_BAMAKO = 6;
    case TMZ_007_AFRICA_BANGUI = 7;
    case TMZ_008_AFRICA_BANJUL = 8;
    case TMZ_009_AFRICA_BISSAU = 9;
    case TMZ_010_AFRICA_BLANTYRE = 10;
    case TMZ_011_AFRICA_BRAZZAVILLE = 11;
    case TMZ_012_AFRICA_BUJUMBURA = 12;
    case TMZ_013_AFRICA_CAIRO = 13;
    case TMZ_014_AFRICA_CASABLANCA = 14;
    case TMZ_015_AFRICA_CEUTA = 15;
    case TMZ_016_AFRICA_CONAKRY = 16;
    case TMZ_017_AFRICA_DAKAR = 17;
    case TMZ_018_AFRICA_DAR_ES_SALAAM = 18;
    case TMZ_019_AFRICA_DJIBOUTI = 19;
    case TMZ_020_AFRICA_DOUALA = 20;
    case TMZ_021_AFRICA_EL_AAIUN = 21;
    case TMZ_022_AFRICA_FREETOWN = 22;
    case TMZ_023_AFRICA_GABORONE = 23;
    case TMZ_024_AFRICA_HARARE = 24;
    case TMZ_025_AFRICA_JOHANNESBURG = 25;
    case TMZ_026_AFRICA_JUBA = 26;
    case TMZ_027_AFRICA_KAMPALA = 27;
    case TMZ_028_AFRICA_KHARTOUM = 28;
    case TMZ_029_AFRICA_KIGALI = 29;
    case TMZ_030_AFRICA_KINSHASA = 30;
    case TMZ_031_AFRICA_LAGOS = 31;
    case TMZ_032_AFRICA_LIBREVILLE = 32;
    case TMZ_033_AFRICA_LOME = 33;
    case TMZ_034_AFRICA_LUANDA = 34;
    case TMZ_035_AFRICA_LUBUMBASHI = 35;
    case TMZ_036_AFRICA_LUSAKA = 36;
    case TMZ_037_AFRICA_MALABO = 37;
    case TMZ_038_AFRICA_MAPUTO = 38;
    case TMZ_039_AFRICA_MASERU = 39;
    case TMZ_040_AFRICA_MBABANE = 40;
    case TMZ_041_AFRICA_MOGADISHU = 41;
    case TMZ_042_AFRICA_MONROVIA = 42;
    case TMZ_043_AFRICA_NAIROBI = 43;
    case TMZ_044_AFRICA_NDJAMENA = 44;
    case TMZ_045_AFRICA_NIAMEY = 45;
    case TMZ_046_AFRICA_NOUAKCHOTT = 46;
    case TMZ_047_AFRICA_OUAGADOUGOU = 47;
    case TMZ_048_AFRICA_PORTO_NOVO = 48;
    case TMZ_049_AFRICA_SAO_TOME = 49;
    case TMZ_050_AFRICA_TIMBUKTU = 50;
    case TMZ_051_AFRICA_TRIPOLI = 51;
    case TMZ_052_AFRICA_TUNIS = 52;
    case TMZ_053_AFRICA_WINDHOEK = 53;
    case TMZ_054_AMERICA_ADAK = 54;
    case TMZ_055_AMERICA_ANCHORAGE = 55;
    case TMZ_056_AMERICA_ANGUILLA = 56;
    case TMZ_057_AMERICA_ANTIGUA = 57;
    case TMZ_058_AMERICA_ARAGUAINA = 58;
    case TMZ_059_AMERICA_ARGENTINA_BUENOS_AIRES = 59;
    case TMZ_060_AMERICA_ARGENTINA_CATAMARCA = 60;
    case TMZ_061_AMERICA_ARGENTINA_COMODRIVADAVIA = 61;
    case TMZ_062_AMERICA_ARGENTINA_CORDOBA = 62;
    case TMZ_063_AMERICA_ARGENTINA_JUJUY = 63;
    case TMZ_064_AMERICA_ARGENTINA_LA_RIOJA = 64;
    case TMZ_065_AMERICA_ARGENTINA_MENDOZA = 65;
    case TMZ_066_AMERICA_ARGENTINA_RIO_GALLEGOS = 66;
    case TMZ_067_AMERICA_ARGENTINA_SALTA = 67;
    case TMZ_068_AMERICA_ARGENTINA_SAN_JUAN = 68;
    case TMZ_069_AMERICA_ARGENTINA_SAN_LUIS = 69;
    case TMZ_070_AMERICA_ARGENTINA_TUCUMAN = 70;
    case TMZ_071_AMERICA_ARGENTINA_USHUAIA = 71;
    case TMZ_072_AMERICA_ARUBA = 72;
    case TMZ_073_AMERICA_ASUNCION = 73;
    case TMZ_074_AMERICA_ATIKOKAN = 74;
    case TMZ_075_AMERICA_ATKA = 75;
    case TMZ_076_AMERICA_BAHIA = 76;
    case TMZ_077_AMERICA_BAHIA_BANDERAS = 77;
    case TMZ_078_AMERICA_BARBADOS = 78;
    case TMZ_079_AMERICA_BELEM = 79;
    case TMZ_080_AMERICA_BELIZE = 80;
    case TMZ_081_AMERICA_BLANC_SABLON = 81;
    case TMZ_082_AMERICA_BOA_VISTA = 82;
    case TMZ_083_AMERICA_BOGOTA = 83;
    case TMZ_084_AMERICA_BOISE = 84;
    case TMZ_085_AMERICA_BUENOS_AIRES = 85;
    case TMZ_086_AMERICA_CAMBRIDGE_BAY = 86;
    case TMZ_087_AMERICA_CAMPO_GRANDE = 87;
    case TMZ_088_AMERICA_CANCUN = 88;
    case TMZ_089_AMERICA_CARACAS = 89;
    case TMZ_090_AMERICA_CATAMARCA = 90;
    case TMZ_091_AMERICA_CAYENNE = 91;
    case TMZ_092_AMERICA_CAYMAN = 92;
    case TMZ_093_AMERICA_CHICAGO = 93;
    case TMZ_094_AMERICA_CHIHUAHUA = 94;
    case TMZ_095_AMERICA_CORAL_HARBOUR = 95;
    case TMZ_096_AMERICA_CORDOBA = 96;
    case TMZ_097_AMERICA_COSTA_RICA = 97;
    case TMZ_098_AMERICA_CRESTON = 98;
    case TMZ_099_AMERICA_CUIABA = 99;
    case TMZ_100_AMERICA_CURACAO = 100;
    case TMZ_101_AMERICA_DANMARKSHAVN = 101;
    case TMZ_102_AMERICA_DAWSON = 102;
    case TMZ_103_AMERICA_DAWSON_CREEK = 103;
    case TMZ_104_AMERICA_DENVER = 104;
    case TMZ_105_AMERICA_DETROIT = 105;
    case TMZ_106_AMERICA_DOMINICA = 106;
    case TMZ_107_AMERICA_EDMONTON = 107;
    case TMZ_108_AMERICA_EIRUNEPE = 108;
    case TMZ_109_AMERICA_EL_SALVADOR = 109;
    case TMZ_110_AMERICA_ENSENADA = 110;
    case TMZ_111_AMERICA_FORT_NELSON = 111;
    case TMZ_112_AMERICA_FORT_WAYNE = 112;
    case TMZ_113_AMERICA_FORTALEZA = 113;
    case TMZ_114_AMERICA_GLACE_BAY = 114;
    case TMZ_115_AMERICA_GODTHAB = 115;
    case TMZ_116_AMERICA_GOOSE_BAY = 116;
    case TMZ_117_AMERICA_GRAND_TURK = 117;
    case TMZ_118_AMERICA_GRENADA = 118;
    case TMZ_119_AMERICA_GUADELOUPE = 119;
    case TMZ_120_AMERICA_GUATEMALA = 120;
    case TMZ_121_AMERICA_GUAYAQUIL = 121;
    case TMZ_122_AMERICA_GUYANA = 122;
    case TMZ_123_AMERICA_HALIFAX = 123;
    case TMZ_124_AMERICA_HAVANA = 124;
    case TMZ_125_AMERICA_HERMOSILLO = 125;
    case TMZ_126_AMERICA_INDIANA_INDIANAPOLIS = 126;
    case TMZ_127_AMERICA_INDIANA_KNOX = 127;
    case TMZ_128_AMERICA_INDIANA_MARENGO = 128;
    case TMZ_129_AMERICA_INDIANA_PETERSBURG = 129;
    case TMZ_130_AMERICA_INDIANA_TELL_CITY = 130;
    case TMZ_131_AMERICA_INDIANA_VEVAY = 131;
    case TMZ_132_AMERICA_INDIANA_VINCENNES = 132;
    case TMZ_133_AMERICA_INDIANA_WINAMAC = 133;
    case TMZ_134_AMERICA_INDIANAPOLIS = 134;
    case TMZ_135_AMERICA_INUVIK = 135;
    case TMZ_136_AMERICA_IQALUIT = 136;
    case TMZ_137_AMERICA_JAMAICA = 137;
    case TMZ_138_AMERICA_JUJUY = 138;
    case TMZ_139_AMERICA_JUNEAU = 139;
    case TMZ_140_AMERICA_KENTUCKY_LOUISVILLE = 140;
    case TMZ_141_AMERICA_KENTUCKY_MONTICELLO = 141;
    case TMZ_142_AMERICA_KNOX_IN = 142;
    case TMZ_143_AMERICA_KRALENDIJK = 143;
    case TMZ_144_AMERICA_LA_PAZ = 144;
    case TMZ_145_AMERICA_LIMA = 145;
    case TMZ_146_AMERICA_LOS_ANGELES = 146;
    case TMZ_147_AMERICA_LOUISVILLE = 147;
    case TMZ_148_AMERICA_LOWER_PRINCES = 148;
    case TMZ_149_AMERICA_MACEIO = 149;
    case TMZ_150_AMERICA_MANAGUA = 150;
    case TMZ_151_AMERICA_MANAUS = 151;
    case TMZ_152_AMERICA_MARIGOT = 152;
    case TMZ_153_AMERICA_MARTINIQUE = 153;
    case TMZ_154_AMERICA_MATAMOROS = 154;
    case TMZ_155_AMERICA_MAZATLAN = 155;
    case TMZ_156_AMERICA_MENDOZA = 156;
    case TMZ_157_AMERICA_MENOMINEE = 157;
    case TMZ_158_AMERICA_MERIDA = 158;
    case TMZ_159_AMERICA_METLAKATLA = 159;
    case TMZ_160_AMERICA_MEXICO_CITY = 160;
    case TMZ_161_AMERICA_MIQUELON = 161;
    case TMZ_162_AMERICA_MONCTON = 162;
    case TMZ_163_AMERICA_MONTERREY = 163;
    case TMZ_164_AMERICA_MONTEVIDEO = 164;
    case TMZ_165_AMERICA_MONTREAL = 165;
    case TMZ_166_AMERICA_MONTSERRAT = 166;
    case TMZ_167_AMERICA_NASSAU = 167;
    case TMZ_168_AMERICA_NEW_YORK = 168;
    case TMZ_169_AMERICA_NIPIGON = 169;
    case TMZ_170_AMERICA_NOME = 170;
    case TMZ_171_AMERICA_NORONHA = 171;
    case TMZ_172_AMERICA_NORTH_DAKOTA_BEULAH = 172;
    case TMZ_173_AMERICA_NORTH_DAKOTA_CENTER = 173;
    case TMZ_174_AMERICA_NORTH_DAKOTA_NEW_SALEM = 174;
    case TMZ_175_AMERICA_OJINAGA = 175;
    case TMZ_176_AMERICA_PANAMA = 176;
    case TMZ_177_AMERICA_PANGNIRTUNG = 177;
    case TMZ_178_AMERICA_PARAMARIBO = 178;
    case TMZ_179_AMERICA_PHOENIX = 179;
    case TMZ_180_AMERICA_PORT_AU_PRINCE = 180;
    case TMZ_181_AMERICA_PORT_OF_SPAIN = 181;
    case TMZ_182_AMERICA_PORTO_ACRE = 182;
    case TMZ_183_AMERICA_PORTO_VELHO = 183;
    case TMZ_184_AMERICA_PUERTO_RICO = 184;
    case TMZ_185_AMERICA_RAINY_RIVER = 185;
    case TMZ_186_AMERICA_RANKIN_INLET = 186;
    case TMZ_187_AMERICA_RECIFE = 187;
    case TMZ_188_AMERICA_REGINA = 188;
    case TMZ_189_AMERICA_RESOLUTE = 189;
    case TMZ_190_AMERICA_RIO_BRANCO = 190;
    case TMZ_191_AMERICA_ROSARIO = 191;
    case TMZ_192_AMERICA_SANTA_ISABEL = 192;
    case TMZ_193_AMERICA_SANTAREM = 193;
    case TMZ_194_AMERICA_SANTIAGO = 194;
    case TMZ_195_AMERICA_SANTO_DOMINGO = 195;
    case TMZ_196_AMERICA_SAO_PAULO = 196;
    case TMZ_197_AMERICA_SCORESBYSUND = 197;
    case TMZ_198_AMERICA_SHIPROCK = 198;
    case TMZ_199_AMERICA_SITKA = 199;
    case TMZ_200_AMERICA_ST_BARTHELEMY = 200;
    case TMZ_201_AMERICA_ST_JOHNS = 201;
    case TMZ_202_AMERICA_ST_KITTS = 202;
    case TMZ_203_AMERICA_ST_LUCIA = 203;
    case TMZ_204_AMERICA_ST_THOMAS = 204;
    case TMZ_205_AMERICA_ST_VINCENT = 205;
    case TMZ_206_AMERICA_SWIFT_CURRENT = 206;
    case TMZ_207_AMERICA_TEGUCIGALPA = 207;
    case TMZ_208_AMERICA_THULE = 208;
    case TMZ_209_AMERICA_THUNDER_BAY = 209;
    case TMZ_210_AMERICA_TIJUANA = 210;
    case TMZ_211_AMERICA_TORONTO = 211;
    case TMZ_212_AMERICA_TORTOLA = 212;
    case TMZ_213_AMERICA_VANCOUVER = 213;
    case TMZ_214_AMERICA_VIRGIN = 214;
    case TMZ_215_AMERICA_WHITEHORSE = 215;
    case TMZ_216_AMERICA_WINNIPEG = 216;
    case TMZ_217_AMERICA_YAKUTAT = 217;
    case TMZ_218_AMERICA_YELLOWKNIFE = 218;
    case TMZ_219_ANTARCTICA_CASEY = 219;
    case TMZ_220_ANTARCTICA_DAVIS = 220;
    case TMZ_221_ANTARCTICA_DUMONTDURVILLE = 221;
    case TMZ_222_ANTARCTICA_MACQUARIE = 222;
    case TMZ_223_ANTARCTICA_MAWSON = 223;
    case TMZ_224_ANTARCTICA_MCMURDO = 224;
    case TMZ_225_ANTARCTICA_PALMER = 225;
    case TMZ_226_ANTARCTICA_ROTHERA = 226;
    case TMZ_227_ANTARCTICA_SOUTH_POLE = 227;
    case TMZ_228_ANTARCTICA_SYOWA = 228;
    case TMZ_229_ANTARCTICA_TROLL = 229;
    case TMZ_230_ANTARCTICA_VOSTOK = 230;
    case TMZ_231_ARCTIC_LONGYEARBYEN = 231;
    case TMZ_232_ASIA_ADEN = 232;
    case TMZ_233_ASIA_ALMATY = 233;
    case TMZ_234_ASIA_AMMAN = 234;
    case TMZ_235_ASIA_ANADYR = 235;
    case TMZ_236_ASIA_AQTAU = 236;
    case TMZ_237_ASIA_AQTOBE = 237;
    case TMZ_238_ASIA_ASHGABAT = 238;
    case TMZ_239_ASIA_ASHKHABAD = 239;
    case TMZ_240_ASIA_BAGHDAD = 240;
    case TMZ_241_ASIA_BAHRAIN = 241;
    case TMZ_242_ASIA_BAKU = 242;
    case TMZ_243_ASIA_BANGKOK = 243;
    case TMZ_244_ASIA_BEIRUT = 244;
    case TMZ_245_ASIA_BISHKEK = 245;
    case TMZ_246_ASIA_BRUNEI = 246;
    case TMZ_247_ASIA_CALCUTTA = 247;
    case TMZ_248_ASIA_CHITA = 248;
    case TMZ_249_ASIA_CHOIBALSAN = 249;
    case TMZ_250_ASIA_CHONGQING = 250;
    case TMZ_251_ASIA_CHUNGKING = 251;
    case TMZ_252_ASIA_COLOMBO = 252;
    case TMZ_253_ASIA_DACCA = 253;
    case TMZ_254_ASIA_DAMASCUS = 254;
    case TMZ_255_ASIA_DHAKA = 255;
    case TMZ_256_ASIA_DILI = 256;
    case TMZ_257_ASIA_DUBAI = 257;
    case TMZ_258_ASIA_DUSHANBE = 258;
    case TMZ_259_ASIA_GAZA = 259;
    case TMZ_260_ASIA_HARBIN = 260;
    case TMZ_261_ASIA_HEBRON = 261;
    case TMZ_262_ASIA_HO_CHI_MINH = 262;
    case TMZ_263_ASIA_HONG_KONG = 263;
    case TMZ_264_ASIA_HOVD = 264;
    case TMZ_265_ASIA_IRKUTSK = 265;
    case TMZ_266_ASIA_ISTANBUL = 266;
    case TMZ_267_ASIA_JAKARTA = 267;
    case TMZ_268_ASIA_JAYAPURA = 268;
    case TMZ_269_ASIA_JERUSALEM = 269;
    case TMZ_270_ASIA_KABUL = 270;
    case TMZ_271_ASIA_KAMCHATKA = 271;
    case TMZ_272_ASIA_KARACHI = 272;
    case TMZ_273_ASIA_KASHGAR = 273;
    case TMZ_274_ASIA_KATHMANDU = 274;
    case TMZ_275_ASIA_KATMANDU = 275;
    case TMZ_276_ASIA_KHANDYGA = 276;
    case TMZ_277_ASIA_KOLKATA = 277;
    case TMZ_278_ASIA_KRASNOYARSK = 278;
    case TMZ_279_ASIA_KUALA_LUMPUR = 279;
    case TMZ_280_ASIA_KUCHING = 280;
    case TMZ_281_ASIA_KUWAIT = 281;
    case TMZ_282_ASIA_MACAO = 282;
    case TMZ_283_ASIA_MACAU = 283;
    case TMZ_284_ASIA_MAGADAN = 284;
    case TMZ_285_ASIA_MAKASSAR = 285;
    case TMZ_286_ASIA_MANILA = 286;
    case TMZ_287_ASIA_MUSCAT = 287;
    case TMZ_288_ASIA_NICOSIA = 288;
    case TMZ_289_ASIA_NOVOKUZNETSK = 289;
    case TMZ_290_ASIA_NOVOSIBIRSK = 290;
    case TMZ_291_ASIA_OMSK = 291;
    case TMZ_292_ASIA_ORAL = 292;
    case TMZ_293_ASIA_PHNOM_PENH = 293;
    case TMZ_294_ASIA_PONTIANAK = 294;
    case TMZ_295_ASIA_PYONGYANG = 295;
    case TMZ_296_ASIA_QATAR = 296;
    case TMZ_297_ASIA_QYZYLORDA = 297;
    case TMZ_298_ASIA_RANGOON = 298;
    case TMZ_299_ASIA_RIYADH = 299;
    case TMZ_300_ASIA_SAIGON = 300;
    case TMZ_301_ASIA_SAKHALIN = 301;
    case TMZ_302_ASIA_SAMARKAND = 302;
    case TMZ_303_ASIA_SEOUL = 303;
    case TMZ_304_ASIA_SHANGHAI = 304;
    case TMZ_305_ASIA_SINGAPORE = 305;
    case TMZ_306_ASIA_SREDNEKOLYMSK = 306;
    case TMZ_307_ASIA_TAIPEI = 307;
    case TMZ_308_ASIA_TASHKENT = 308;
    case TMZ_309_ASIA_TBILISI = 309;
    case TMZ_310_ASIA_TEHRAN = 310;
    case TMZ_311_ASIA_TEL_AVIV = 311;
    case TMZ_312_ASIA_THIMBU = 312;
    case TMZ_313_ASIA_THIMPHU = 313;
    case TMZ_314_ASIA_TOKYO = 314;
    case TMZ_315_ASIA_UJUNG_PANDANG = 315;
    case TMZ_316_ASIA_ULAANBAATAR = 316;
    case TMZ_317_ASIA_ULAN_BATOR = 317;
    case TMZ_318_ASIA_URUMQI = 318;
    case TMZ_319_ASIA_UST_NERA = 319;
    case TMZ_320_ASIA_VIENTIANE = 320;
    case TMZ_321_ASIA_VLADIVOSTOK = 321;
    case TMZ_322_ASIA_YAKUTSK = 322;
    case TMZ_323_ASIA_YEKATERINBURG = 323;
    case TMZ_324_ASIA_YEREVAN = 324;
    case TMZ_325_ATLANTIC_AZORES = 325;
    case TMZ_326_ATLANTIC_BERMUDA = 326;
    case TMZ_327_ATLANTIC_CANARY = 327;
    case TMZ_328_ATLANTIC_CAPE_VERDE = 328;
    case TMZ_329_ATLANTIC_FAEROE = 329;
    case TMZ_330_ATLANTIC_FAROE = 330;
    case TMZ_331_ATLANTIC_JAN_MAYEN = 331;
    case TMZ_332_ATLANTIC_MADEIRA = 332;
    case TMZ_333_ATLANTIC_REYKJAVIK = 333;
    case TMZ_334_ATLANTIC_SOUTH_GEORGIA = 334;
    case TMZ_335_ATLANTIC_ST_HELENA = 335;
    case TMZ_336_ATLANTIC_STANLEY = 336;
    case TMZ_337_AUSTRALIA_ACT = 337;
    case TMZ_338_AUSTRALIA_ADELAIDE = 338;
    case TMZ_339_AUSTRALIA_BRISBANE = 339;
    case TMZ_340_AUSTRALIA_BROKEN_HILL = 340;
    case TMZ_341_AUSTRALIA_CANBERRA = 341;
    case TMZ_342_AUSTRALIA_CURRIE = 342;
    case TMZ_343_AUSTRALIA_DARWIN = 343;
    case TMZ_344_AUSTRALIA_EUCLA = 344;
    case TMZ_345_AUSTRALIA_HOBART = 345;
    case TMZ_346_AUSTRALIA_LHI = 346;
    case TMZ_347_AUSTRALIA_LINDEMAN = 347;
    case TMZ_348_AUSTRALIA_LORD_HOWE = 348;
    case TMZ_349_AUSTRALIA_MELBOURNE = 349;
    case TMZ_350_AUSTRALIA_NSW = 350;
    case TMZ_351_AUSTRALIA_NORTH = 351;
    case TMZ_352_AUSTRALIA_PERTH = 352;
    case TMZ_353_AUSTRALIA_QUEENSLAND = 353;
    case TMZ_354_AUSTRALIA_SOUTH = 354;
    case TMZ_355_AUSTRALIA_SYDNEY = 355;
    case TMZ_356_AUSTRALIA_TASMANIA = 356;
    case TMZ_357_AUSTRALIA_VICTORIA = 357;
    case TMZ_358_AUSTRALIA_WEST = 358;
    case TMZ_359_AUSTRALIA_YANCOWINNA = 359;
    case TMZ_360_BRAZIL_ACRE = 360;
    case TMZ_361_BRAZIL_DENORONHA = 361;
    case TMZ_362_BRAZIL_EAST = 362;
    case TMZ_363_BRAZIL_WEST = 363;
    case TMZ_364_CET = 364;
    case TMZ_365_CST6CDT = 365;
    case TMZ_366_CANADA_ATLANTIC = 366;
    case TMZ_367_CANADA_CENTRAL = 367;
    case TMZ_368_CANADA_EAST_SASKATCHEWAN = 368;
    case TMZ_369_CANADA_EASTERN = 369;
    case TMZ_370_CANADA_MOUNTAIN = 370;
    case TMZ_371_CANADA_NEWFOUNDLAND = 371;
    case TMZ_372_CANADA_PACIFIC = 372;
    case TMZ_373_CANADA_SASKATCHEWAN = 373;
    case TMZ_374_CANADA_YUKON = 374;
    case TMZ_375_CHILE_CONTINENTAL = 375;
    case TMZ_376_CHILE_EASTERISLAND = 376;
    case TMZ_377_CUBA = 377;
    case TMZ_378_EET = 378;
    case TMZ_379_EST = 379;
    case TMZ_380_EST5EDT = 380;
    case TMZ_381_EGYPT = 381;
    case TMZ_382_EIRE = 382;
    case TMZ_383_ETC_GMT = 383;
    case TMZ_384_ETC_GMT_0 = 384;
    case TMZ_385_ETC_GMT_1 = 385;
    case TMZ_386_ETC_GMT_10 = 386;
    case TMZ_387_ETC_GMT_11 = 387;
    case TMZ_388_ETC_GMT_12 = 388;
    case TMZ_389_ETC_GMT_2 = 389;
    case TMZ_390_ETC_GMT_3 = 390;
    case TMZ_391_ETC_GMT_4 = 391;
    case TMZ_392_ETC_GMT_5 = 392;
    case TMZ_393_ETC_GMT_6 = 393;
    case TMZ_394_ETC_GMT_7 = 394;
    case TMZ_395_ETC_GMT_8 = 395;
    case TMZ_396_ETC_GMT_9 = 396;
    case TMZ_397_ETC_GMT_0 = 397;
    case TMZ_398_ETC_GMT_1 = 398;
    case TMZ_399_ETC_GMT_10 = 399;
    case TMZ_400_ETC_GMT_11 = 400;
    case TMZ_401_ETC_GMT_12 = 401;
    case TMZ_402_ETC_GMT_13 = 402;
    case TMZ_403_ETC_GMT_14 = 403;
    case TMZ_404_ETC_GMT_2 = 404;
    case TMZ_405_ETC_GMT_3 = 405;
    case TMZ_406_ETC_GMT_4 = 406;
    case TMZ_407_ETC_GMT_5 = 407;
    case TMZ_408_ETC_GMT_6 = 408;
    case TMZ_409_ETC_GMT_7 = 409;
    case TMZ_410_ETC_GMT_8 = 410;
    case TMZ_411_ETC_GMT_9 = 411;
    case TMZ_412_ETC_GMT0 = 412;
    case TMZ_413_ETC_GREENWICH = 413;
    case TMZ_414_ETC_UCT = 414;
    case TMZ_415_ETC_UTC = 415;
    case TMZ_416_ETC_UNIVERSAL = 416;
    case TMZ_417_ETC_ZULU = 417;
    case TMZ_418_EUROPE_AMSTERDAM = 418;
    case TMZ_419_EUROPE_ANDORRA = 419;
    case TMZ_420_EUROPE_ATHENS = 420;
    case TMZ_421_EUROPE_BELFAST = 421;
    case TMZ_422_EUROPE_BELGRADE = 422;
    case TMZ_423_EUROPE_BERLIN = 423;
    case TMZ_424_EUROPE_BRATISLAVA = 424;
    case TMZ_425_EUROPE_BRUSSELS = 425;
    case TMZ_426_EUROPE_BUCHAREST = 426;
    case TMZ_427_EUROPE_BUDAPEST = 427;
    case TMZ_428_EUROPE_BUSINGEN = 428;
    case TMZ_429_EUROPE_CHISINAU = 429;
    case TMZ_430_EUROPE_COPENHAGEN = 430;
    case TMZ_431_EUROPE_DUBLIN = 431;
    case TMZ_432_EUROPE_GIBRALTAR = 432;
    case TMZ_433_EUROPE_GUERNSEY = 433;
    case TMZ_434_EUROPE_HELSINKI = 434;
    case TMZ_435_EUROPE_ISLE_OF_MAN = 435;
    case TMZ_436_EUROPE_ISTANBUL = 436;
    case TMZ_437_EUROPE_JERSEY = 437;
    case TMZ_438_EUROPE_KALININGRAD = 438;
    case TMZ_439_EUROPE_KIEV = 439;
    case TMZ_440_EUROPE_LISBON = 440;
    case TMZ_441_EUROPE_LJUBLJANA = 441;
    case TMZ_442_EUROPE_LONDON = 442;
    case TMZ_443_EUROPE_LUXEMBOURG = 443;
    case TMZ_444_EUROPE_MADRID = 444;
    case TMZ_445_EUROPE_MALTA = 445;
    case TMZ_446_EUROPE_MARIEHAMN = 446;
    case TMZ_447_EUROPE_MINSK = 447;
    case TMZ_448_EUROPE_MONACO = 448;
    case TMZ_449_EUROPE_MOSCOW = 449;
    case TMZ_450_EUROPE_NICOSIA = 450;
    case TMZ_451_EUROPE_OSLO = 451;
    case TMZ_452_EUROPE_PARIS = 452;
    case TMZ_453_EUROPE_PODGORICA = 453;
    case TMZ_454_EUROPE_PRAGUE = 454;
    case TMZ_455_EUROPE_RIGA = 455;
    case TMZ_456_EUROPE_ROME = 456;
    case TMZ_457_EUROPE_SAMARA = 457;
    case TMZ_458_EUROPE_SAN_MARINO = 458;
    case TMZ_459_EUROPE_SARAJEVO = 459;
    case TMZ_460_EUROPE_SIMFEROPOL = 460;
    case TMZ_461_EUROPE_SKOPJE = 461;
    case TMZ_462_EUROPE_SOFIA = 462;
    case TMZ_463_EUROPE_STOCKHOLM = 463;
    case TMZ_464_EUROPE_TALLINN = 464;
    case TMZ_465_EUROPE_TIRANE = 465;
    case TMZ_466_EUROPE_TIRASPOL = 466;
    case TMZ_467_EUROPE_UZHGOROD = 467;
    case TMZ_468_EUROPE_VADUZ = 468;
    case TMZ_469_EUROPE_VATICAN = 469;
    case TMZ_470_EUROPE_VIENNA = 470;
    case TMZ_471_EUROPE_VILNIUS = 471;
    case TMZ_472_EUROPE_VOLGOGRAD = 472;
    case TMZ_473_EUROPE_WARSAW = 473;
    case TMZ_474_EUROPE_ZAGREB = 474;
    case TMZ_475_EUROPE_ZAPOROZHYE = 475;
    case TMZ_476_EUROPE_ZURICH = 476;
    case TMZ_477_FACTORY = 477;
    case TMZ_478_GB = 478;
    case TMZ_479_GB_EIRE = 479;
    case TMZ_480_GMT = 480;
    case TMZ_481_GMT_0 = 481;
    case TMZ_482_GMT_0 = 482;
    case TMZ_483_GMT0 = 483;
    case TMZ_484_GREENWICH = 484;
    case TMZ_485_HST = 485;
    case TMZ_486_HONGKONG = 486;
    case TMZ_487_ICELAND = 487;
    case TMZ_488_INDIAN_ANTANANARIVO = 488;
    case TMZ_489_INDIAN_CHAGOS = 489;
    case TMZ_490_INDIAN_CHRISTMAS = 490;
    case TMZ_491_INDIAN_COCOS = 491;
    case TMZ_492_INDIAN_COMORO = 492;
    case TMZ_493_INDIAN_KERGUELEN = 493;
    case TMZ_494_INDIAN_MAHE = 494;
    case TMZ_495_INDIAN_MALDIVES = 495;
    case TMZ_496_INDIAN_MAURITIUS = 496;
    case TMZ_497_INDIAN_MAYOTTE = 497;
    case TMZ_498_INDIAN_REUNION = 498;
    case TMZ_499_IRAN = 499;
    case TMZ_500_ISRAEL = 500;
    case TMZ_501_JAMAICA = 501;
    case TMZ_502_JAPAN = 502;
    case TMZ_503_KWAJALEIN = 503;
    case TMZ_504_LIBYA = 504;
    case TMZ_505_MET = 505;
    case TMZ_506_MST = 506;
    case TMZ_507_MST7MDT = 507;
    case TMZ_508_MEXICO_BAJANORTE = 508;
    case TMZ_509_MEXICO_BAJASUR = 509;
    case TMZ_510_MEXICO_GENERAL = 510;
    case TMZ_511_NZ = 511;
    case TMZ_512_NZ_CHAT = 512;
    case TMZ_513_NAVAJO = 513;
    case TMZ_514_PRC = 514;
    case TMZ_515_PST8PDT = 515;
    case TMZ_516_PACIFIC_APIA = 516;
    case TMZ_517_PACIFIC_AUCKLAND = 517;
    case TMZ_518_PACIFIC_BOUGAINVILLE = 518;
    case TMZ_519_PACIFIC_CHATHAM = 519;
    case TMZ_520_PACIFIC_CHUUK = 520;
    case TMZ_521_PACIFIC_EASTER = 521;
    case TMZ_522_PACIFIC_EFATE = 522;
    case TMZ_523_PACIFIC_ENDERBURY = 523;
    case TMZ_524_PACIFIC_FAKAOFO = 524;
    case TMZ_525_PACIFIC_FIJI = 525;
    case TMZ_526_PACIFIC_FUNAFUTI = 526;
    case TMZ_527_PACIFIC_GALAPAGOS = 527;
    case TMZ_528_PACIFIC_GAMBIER = 528;
    case TMZ_529_PACIFIC_GUADALCANAL = 529;
    case TMZ_530_PACIFIC_GUAM = 530;
    case TMZ_531_PACIFIC_HONOLULU = 531;
    case TMZ_532_PACIFIC_JOHNSTON = 532;
    case TMZ_533_PACIFIC_KIRITIMATI = 533;
    case TMZ_534_PACIFIC_KOSRAE = 534;
    case TMZ_535_PACIFIC_KWAJALEIN = 535;
    case TMZ_536_PACIFIC_MAJURO = 536;
    case TMZ_537_PACIFIC_MARQUESAS = 537;
    case TMZ_538_PACIFIC_MIDWAY = 538;
    case TMZ_539_PACIFIC_NAURU = 539;
    case TMZ_540_PACIFIC_NIUE = 540;
    case TMZ_541_PACIFIC_NORFOLK = 541;
    case TMZ_542_PACIFIC_NOUMEA = 542;
    case TMZ_543_PACIFIC_PAGO_PAGO = 543;
    case TMZ_544_PACIFIC_PALAU = 544;
    case TMZ_545_PACIFIC_PITCAIRN = 545;
    case TMZ_546_PACIFIC_POHNPEI = 546;
    case TMZ_547_PACIFIC_PONAPE = 547;
    case TMZ_548_PACIFIC_PORT_MORESBY = 548;
    case TMZ_549_PACIFIC_RAROTONGA = 549;
    case TMZ_550_PACIFIC_SAIPAN = 550;
    case TMZ_551_PACIFIC_SAMOA = 551;
    case TMZ_552_PACIFIC_TAHITI = 552;
    case TMZ_553_PACIFIC_TARAWA = 553;
    case TMZ_554_PACIFIC_TONGATAPU = 554;
    case TMZ_555_PACIFIC_TRUK = 555;
    case TMZ_556_PACIFIC_WAKE = 556;
    case TMZ_557_PACIFIC_WALLIS = 557;
    case TMZ_558_PACIFIC_YAP = 558;
    case TMZ_559_POLAND = 559;
    case TMZ_560_PORTUGAL = 560;
    case TMZ_561_ROC = 561;
    case TMZ_562_ROK = 562;
    case TMZ_563_SINGAPORE = 563;
    case TMZ_564_TURKEY = 564;
    case TMZ_565_US_ALASKA = 565;
    case TMZ_566_US_ALEUTIAN = 566;
    case TMZ_567_US_ARIZONA = 567;
    case TMZ_568_US_CENTRAL = 568;
    case TMZ_569_US_EAST_INDIANA = 569;
    case TMZ_570_US_EASTERN = 570;
    case TMZ_571_US_HAWAII = 571;
    case TMZ_572_US_INDIANA_STARKE = 572;
    case TMZ_573_US_MICHIGAN = 573;
    case TMZ_574_US_MOUNTAIN = 574;
    case TMZ_575_US_PACIFIC = 575;
    case TMZ_576_US_PACIFIC_NEW = 576;
    case TMZ_577_US_SAMOA = 577;
    case TMZ_578_UTC = 578;
    case TMZ_579_UNIVERSAL = 579;
    case TMZ_580_W_SU = 580;
    case TMZ_581_WET = 581;
    case TMZ_582_ZULU = 582;


    public function timezone(): string
    {
        return match ($this) {
            self::TMZ_000_AFRICA_ABIDJAN => 'Africa/Abidjan',
            self::TMZ_001_AFRICA_ACCRA => 'Africa/Accra',
            self::TMZ_002_AFRICA_ADDIS_ABABA => 'Africa/Addis_Ababa',
            self::TMZ_003_AFRICA_ALGIERS => 'Africa/Algiers',
            self::TMZ_004_AFRICA_ASMARA => 'Africa/Asmara',
            self::TMZ_005_AFRICA_ASMERA => 'Africa/Asmera',
            self::TMZ_006_AFRICA_BAMAKO => 'Africa/Bamako',
            self::TMZ_007_AFRICA_BANGUI => 'Africa/Bangui',
            self::TMZ_008_AFRICA_BANJUL => 'Africa/Banjul',
            self::TMZ_009_AFRICA_BISSAU => 'Africa/Bissau',
            self::TMZ_010_AFRICA_BLANTYRE => 'Africa/Blantyre',
            self::TMZ_011_AFRICA_BRAZZAVILLE => 'Africa/Brazzaville',
            self::TMZ_012_AFRICA_BUJUMBURA => 'Africa/Bujumbura',
            self::TMZ_013_AFRICA_CAIRO => 'Africa/Cairo',
            self::TMZ_014_AFRICA_CASABLANCA => 'Africa/Casablanca',
            self::TMZ_015_AFRICA_CEUTA => 'Africa/Ceuta',
            self::TMZ_016_AFRICA_CONAKRY => 'Africa/Conakry',
            self::TMZ_017_AFRICA_DAKAR => 'Africa/Dakar',
            self::TMZ_018_AFRICA_DAR_ES_SALAAM => 'Africa/Dar_es_Salaam',
            self::TMZ_019_AFRICA_DJIBOUTI => 'Africa/Djibouti',
            self::TMZ_020_AFRICA_DOUALA => 'Africa/Douala',
            self::TMZ_021_AFRICA_EL_AAIUN => 'Africa/El_Aaiun',
            self::TMZ_022_AFRICA_FREETOWN => 'Africa/Freetown',
            self::TMZ_023_AFRICA_GABORONE => 'Africa/Gaborone',
            self::TMZ_024_AFRICA_HARARE => 'Africa/Harare',
            self::TMZ_025_AFRICA_JOHANNESBURG => 'Africa/Johannesburg',
            self::TMZ_026_AFRICA_JUBA => 'Africa/Juba',
            self::TMZ_027_AFRICA_KAMPALA => 'Africa/Kampala',
            self::TMZ_028_AFRICA_KHARTOUM => 'Africa/Khartoum',
            self::TMZ_029_AFRICA_KIGALI => 'Africa/Kigali',
            self::TMZ_030_AFRICA_KINSHASA => 'Africa/Kinshasa',
            self::TMZ_031_AFRICA_LAGOS => 'Africa/Lagos',
            self::TMZ_032_AFRICA_LIBREVILLE => 'Africa/Libreville',
            self::TMZ_033_AFRICA_LOME => 'Africa/Lome',
            self::TMZ_034_AFRICA_LUANDA => 'Africa/Luanda',
            self::TMZ_035_AFRICA_LUBUMBASHI => 'Africa/Lubumbashi',
            self::TMZ_036_AFRICA_LUSAKA => 'Africa/Lusaka',
            self::TMZ_037_AFRICA_MALABO => 'Africa/Malabo',
            self::TMZ_038_AFRICA_MAPUTO => 'Africa/Maputo',
            self::TMZ_039_AFRICA_MASERU => 'Africa/Maseru',
            self::TMZ_040_AFRICA_MBABANE => 'Africa/Mbabane',
            self::TMZ_041_AFRICA_MOGADISHU => 'Africa/Mogadishu',
            self::TMZ_042_AFRICA_MONROVIA => 'Africa/Monrovia',
            self::TMZ_043_AFRICA_NAIROBI => 'Africa/Nairobi',
            self::TMZ_044_AFRICA_NDJAMENA => 'Africa/Ndjamena',
            self::TMZ_045_AFRICA_NIAMEY => 'Africa/Niamey',
            self::TMZ_046_AFRICA_NOUAKCHOTT => 'Africa/Nouakchott',
            self::TMZ_047_AFRICA_OUAGADOUGOU => 'Africa/Ouagadougou',
            self::TMZ_048_AFRICA_PORTO_NOVO => 'Africa/Porto-Novo',
            self::TMZ_049_AFRICA_SAO_TOME => 'Africa/Sao_Tome',
            self::TMZ_050_AFRICA_TIMBUKTU => 'Africa/Timbuktu',
            self::TMZ_051_AFRICA_TRIPOLI => 'Africa/Tripoli',
            self::TMZ_052_AFRICA_TUNIS => 'Africa/Tunis',
            self::TMZ_053_AFRICA_WINDHOEK => 'Africa/Windhoek',
            self::TMZ_054_AMERICA_ADAK => 'America/Adak',
            self::TMZ_055_AMERICA_ANCHORAGE => 'America/Anchorage',
            self::TMZ_056_AMERICA_ANGUILLA => 'America/Anguilla',
            self::TMZ_057_AMERICA_ANTIGUA => 'America/Antigua',
            self::TMZ_058_AMERICA_ARAGUAINA => 'America/Araguaina',
            self::TMZ_059_AMERICA_ARGENTINA_BUENOS_AIRES => 'America/Argentina/Buenos_Aires',
            self::TMZ_060_AMERICA_ARGENTINA_CATAMARCA => 'America/Argentina/Catamarca',
            self::TMZ_061_AMERICA_ARGENTINA_COMODRIVADAVIA => 'America/Argentina/ComodRivadavia',
            self::TMZ_062_AMERICA_ARGENTINA_CORDOBA => 'America/Argentina/Cordoba',
            self::TMZ_063_AMERICA_ARGENTINA_JUJUY => 'America/Argentina/Jujuy',
            self::TMZ_064_AMERICA_ARGENTINA_LA_RIOJA => 'America/Argentina/La_Rioja',
            self::TMZ_065_AMERICA_ARGENTINA_MENDOZA => 'America/Argentina/Mendoza',
            self::TMZ_066_AMERICA_ARGENTINA_RIO_GALLEGOS => 'America/Argentina/Rio_Gallegos',
            self::TMZ_067_AMERICA_ARGENTINA_SALTA => 'America/Argentina/Salta',
            self::TMZ_068_AMERICA_ARGENTINA_SAN_JUAN => 'America/Argentina/San_Juan',
            self::TMZ_069_AMERICA_ARGENTINA_SAN_LUIS => 'America/Argentina/San_Luis',
            self::TMZ_070_AMERICA_ARGENTINA_TUCUMAN => 'America/Argentina/Tucuman',
            self::TMZ_071_AMERICA_ARGENTINA_USHUAIA => 'America/Argentina/Ushuaia',
            self::TMZ_072_AMERICA_ARUBA => 'America/Aruba',
            self::TMZ_073_AMERICA_ASUNCION => 'America/Asuncion',
            self::TMZ_074_AMERICA_ATIKOKAN => 'America/Atikokan',
            self::TMZ_075_AMERICA_ATKA => 'America/Atka',
            self::TMZ_076_AMERICA_BAHIA => 'America/Bahia',
            self::TMZ_077_AMERICA_BAHIA_BANDERAS => 'America/Bahia_Banderas',
            self::TMZ_078_AMERICA_BARBADOS => 'America/Barbados',
            self::TMZ_079_AMERICA_BELEM => 'America/Belem',
            self::TMZ_080_AMERICA_BELIZE => 'America/Belize',
            self::TMZ_081_AMERICA_BLANC_SABLON => 'America/Blanc-Sablon',
            self::TMZ_082_AMERICA_BOA_VISTA => 'America/Boa_Vista',
            self::TMZ_083_AMERICA_BOGOTA => 'America/Bogota',
            self::TMZ_084_AMERICA_BOISE => 'America/Boise',
            self::TMZ_085_AMERICA_BUENOS_AIRES => 'America/Buenos_Aires',
            self::TMZ_086_AMERICA_CAMBRIDGE_BAY => 'America/Cambridge_Bay',
            self::TMZ_087_AMERICA_CAMPO_GRANDE => 'America/Campo_Grande',
            self::TMZ_088_AMERICA_CANCUN => 'America/Cancun',
            self::TMZ_089_AMERICA_CARACAS => 'America/Caracas',
            self::TMZ_090_AMERICA_CATAMARCA => 'America/Catamarca',
            self::TMZ_091_AMERICA_CAYENNE => 'America/Cayenne',
            self::TMZ_092_AMERICA_CAYMAN => 'America/Cayman',
            self::TMZ_093_AMERICA_CHICAGO => 'America/Chicago',
            self::TMZ_094_AMERICA_CHIHUAHUA => 'America/Chihuahua',
            self::TMZ_095_AMERICA_CORAL_HARBOUR => 'America/Coral_Harbour',
            self::TMZ_096_AMERICA_CORDOBA => 'America/Cordoba',
            self::TMZ_097_AMERICA_COSTA_RICA => 'America/Costa_Rica',
            self::TMZ_098_AMERICA_CRESTON => 'America/Creston',
            self::TMZ_099_AMERICA_CUIABA => 'America/Cuiaba',
            self::TMZ_100_AMERICA_CURACAO => 'America/Curacao',
            self::TMZ_101_AMERICA_DANMARKSHAVN => 'America/Danmarkshavn',
            self::TMZ_102_AMERICA_DAWSON => 'America/Dawson',
            self::TMZ_103_AMERICA_DAWSON_CREEK => 'America/Dawson_Creek',
            self::TMZ_104_AMERICA_DENVER => 'America/Denver',
            self::TMZ_105_AMERICA_DETROIT => 'America/Detroit',
            self::TMZ_106_AMERICA_DOMINICA => 'America/Dominica',
            self::TMZ_107_AMERICA_EDMONTON => 'America/Edmonton',
            self::TMZ_108_AMERICA_EIRUNEPE => 'America/Eirunepe',
            self::TMZ_109_AMERICA_EL_SALVADOR => 'America/El_Salvador',
            self::TMZ_110_AMERICA_ENSENADA => 'America/Ensenada',
            self::TMZ_111_AMERICA_FORT_NELSON => 'America/Fort_Nelson',
            self::TMZ_112_AMERICA_FORT_WAYNE => 'America/Fort_Wayne',
            self::TMZ_113_AMERICA_FORTALEZA => 'America/Fortaleza',
            self::TMZ_114_AMERICA_GLACE_BAY => 'America/Glace_Bay',
            self::TMZ_115_AMERICA_GODTHAB => 'America/Godthab',
            self::TMZ_116_AMERICA_GOOSE_BAY => 'America/Goose_Bay',
            self::TMZ_117_AMERICA_GRAND_TURK => 'America/Grand_Turk',
            self::TMZ_118_AMERICA_GRENADA => 'America/Grenada',
            self::TMZ_119_AMERICA_GUADELOUPE => 'America/Guadeloupe',
            self::TMZ_120_AMERICA_GUATEMALA => 'America/Guatemala',
            self::TMZ_121_AMERICA_GUAYAQUIL => 'America/Guayaquil',
            self::TMZ_122_AMERICA_GUYANA => 'America/Guyana',
            self::TMZ_123_AMERICA_HALIFAX => 'America/Halifax',
            self::TMZ_124_AMERICA_HAVANA => 'America/Havana',
            self::TMZ_125_AMERICA_HERMOSILLO => 'America/Hermosillo',
            self::TMZ_126_AMERICA_INDIANA_INDIANAPOLIS => 'America/Indiana/Indianapolis',
            self::TMZ_127_AMERICA_INDIANA_KNOX => 'America/Indiana/Knox',
            self::TMZ_128_AMERICA_INDIANA_MARENGO => 'America/Indiana/Marengo',
            self::TMZ_129_AMERICA_INDIANA_PETERSBURG => 'America/Indiana/Petersburg',
            self::TMZ_130_AMERICA_INDIANA_TELL_CITY => 'America/Indiana/Tell_City',
            self::TMZ_131_AMERICA_INDIANA_VEVAY => 'America/Indiana/Vevay',
            self::TMZ_132_AMERICA_INDIANA_VINCENNES => 'America/Indiana/Vincennes',
            self::TMZ_133_AMERICA_INDIANA_WINAMAC => 'America/Indiana/Winamac',
            self::TMZ_134_AMERICA_INDIANAPOLIS => 'America/Indianapolis',
            self::TMZ_135_AMERICA_INUVIK => 'America/Inuvik',
            self::TMZ_136_AMERICA_IQALUIT => 'America/Iqaluit',
            self::TMZ_137_AMERICA_JAMAICA => 'America/Jamaica',
            self::TMZ_138_AMERICA_JUJUY => 'America/Jujuy',
            self::TMZ_139_AMERICA_JUNEAU => 'America/Juneau',
            self::TMZ_140_AMERICA_KENTUCKY_LOUISVILLE => 'America/Kentucky/Louisville',
            self::TMZ_141_AMERICA_KENTUCKY_MONTICELLO => 'America/Kentucky/Monticello',
            self::TMZ_142_AMERICA_KNOX_IN => 'America/Knox_IN',
            self::TMZ_143_AMERICA_KRALENDIJK => 'America/Kralendijk',
            self::TMZ_144_AMERICA_LA_PAZ => 'America/La_Paz',
            self::TMZ_145_AMERICA_LIMA => 'America/Lima',
            self::TMZ_146_AMERICA_LOS_ANGELES => 'America/Los_Angeles',
            self::TMZ_147_AMERICA_LOUISVILLE => 'America/Louisville',
            self::TMZ_148_AMERICA_LOWER_PRINCES => 'America/Lower_Princes',
            self::TMZ_149_AMERICA_MACEIO => 'America/Maceio',
            self::TMZ_150_AMERICA_MANAGUA => 'America/Managua',
            self::TMZ_151_AMERICA_MANAUS => 'America/Manaus',
            self::TMZ_152_AMERICA_MARIGOT => 'America/Marigot',
            self::TMZ_153_AMERICA_MARTINIQUE => 'America/Martinique',
            self::TMZ_154_AMERICA_MATAMOROS => 'America/Matamoros',
            self::TMZ_155_AMERICA_MAZATLAN => 'America/Mazatlan',
            self::TMZ_156_AMERICA_MENDOZA => 'America/Mendoza',
            self::TMZ_157_AMERICA_MENOMINEE => 'America/Menominee',
            self::TMZ_158_AMERICA_MERIDA => 'America/Merida',
            self::TMZ_159_AMERICA_METLAKATLA => 'America/Metlakatla',
            self::TMZ_160_AMERICA_MEXICO_CITY => 'America/Mexico_City',
            self::TMZ_161_AMERICA_MIQUELON => 'America/Miquelon',
            self::TMZ_162_AMERICA_MONCTON => 'America/Moncton',
            self::TMZ_163_AMERICA_MONTERREY => 'America/Monterrey',
            self::TMZ_164_AMERICA_MONTEVIDEO => 'America/Montevideo',
            self::TMZ_165_AMERICA_MONTREAL => 'America/Montreal',
            self::TMZ_166_AMERICA_MONTSERRAT => 'America/Montserrat',
            self::TMZ_167_AMERICA_NASSAU => 'America/Nassau',
            self::TMZ_168_AMERICA_NEW_YORK => 'America/New_York',
            self::TMZ_169_AMERICA_NIPIGON => 'America/Nipigon',
            self::TMZ_170_AMERICA_NOME => 'America/Nome',
            self::TMZ_171_AMERICA_NORONHA => 'America/Noronha',
            self::TMZ_172_AMERICA_NORTH_DAKOTA_BEULAH => 'America/North_Dakota/Beulah',
            self::TMZ_173_AMERICA_NORTH_DAKOTA_CENTER => 'America/North_Dakota/Center',
            self::TMZ_174_AMERICA_NORTH_DAKOTA_NEW_SALEM => 'America/North_Dakota/New_Salem',
            self::TMZ_175_AMERICA_OJINAGA => 'America/Ojinaga',
            self::TMZ_176_AMERICA_PANAMA => 'America/Panama',
            self::TMZ_177_AMERICA_PANGNIRTUNG => 'America/Pangnirtung',
            self::TMZ_178_AMERICA_PARAMARIBO => 'America/Paramaribo',
            self::TMZ_179_AMERICA_PHOENIX => 'America/Phoenix',
            self::TMZ_180_AMERICA_PORT_AU_PRINCE => 'America/Port-au-Prince',
            self::TMZ_181_AMERICA_PORT_OF_SPAIN => 'America/Port_of_Spain',
            self::TMZ_182_AMERICA_PORTO_ACRE => 'America/Porto_Acre',
            self::TMZ_183_AMERICA_PORTO_VELHO => 'America/Porto_Velho',
            self::TMZ_184_AMERICA_PUERTO_RICO => 'America/Puerto_Rico',
            self::TMZ_185_AMERICA_RAINY_RIVER => 'America/Rainy_River',
            self::TMZ_186_AMERICA_RANKIN_INLET => 'America/Rankin_Inlet',
            self::TMZ_187_AMERICA_RECIFE => 'America/Recife',
            self::TMZ_188_AMERICA_REGINA => 'America/Regina',
            self::TMZ_189_AMERICA_RESOLUTE => 'America/Resolute',
            self::TMZ_190_AMERICA_RIO_BRANCO => 'America/Rio_Branco',
            self::TMZ_191_AMERICA_ROSARIO => 'America/Rosario',
            self::TMZ_192_AMERICA_SANTA_ISABEL => 'America/Santa_Isabel',
            self::TMZ_193_AMERICA_SANTAREM => 'America/Santarem',
            self::TMZ_194_AMERICA_SANTIAGO => 'America/Santiago',
            self::TMZ_195_AMERICA_SANTO_DOMINGO => 'America/Santo_Domingo',
            self::TMZ_196_AMERICA_SAO_PAULO => 'America/Sao_Paulo',
            self::TMZ_197_AMERICA_SCORESBYSUND => 'America/Scoresbysund',
            self::TMZ_198_AMERICA_SHIPROCK => 'America/Shiprock',
            self::TMZ_199_AMERICA_SITKA => 'America/Sitka',
            self::TMZ_200_AMERICA_ST_BARTHELEMY => 'America/St_Barthelemy',
            self::TMZ_201_AMERICA_ST_JOHNS => 'America/St_Johns',
            self::TMZ_202_AMERICA_ST_KITTS => 'America/St_Kitts',
            self::TMZ_203_AMERICA_ST_LUCIA => 'America/St_Lucia',
            self::TMZ_204_AMERICA_ST_THOMAS => 'America/St_Thomas',
            self::TMZ_205_AMERICA_ST_VINCENT => 'America/St_Vincent',
            self::TMZ_206_AMERICA_SWIFT_CURRENT => 'America/Swift_Current',
            self::TMZ_207_AMERICA_TEGUCIGALPA => 'America/Tegucigalpa',
            self::TMZ_208_AMERICA_THULE => 'America/Thule',
            self::TMZ_209_AMERICA_THUNDER_BAY => 'America/Thunder_Bay',
            self::TMZ_210_AMERICA_TIJUANA => 'America/Tijuana',
            self::TMZ_211_AMERICA_TORONTO => 'America/Toronto',
            self::TMZ_212_AMERICA_TORTOLA => 'America/Tortola',
            self::TMZ_213_AMERICA_VANCOUVER => 'America/Vancouver',
            self::TMZ_214_AMERICA_VIRGIN => 'America/Virgin',
            self::TMZ_215_AMERICA_WHITEHORSE => 'America/Whitehorse',
            self::TMZ_216_AMERICA_WINNIPEG => 'America/Winnipeg',
            self::TMZ_217_AMERICA_YAKUTAT => 'America/Yakutat',
            self::TMZ_218_AMERICA_YELLOWKNIFE => 'America/Yellowknife',
            self::TMZ_219_ANTARCTICA_CASEY => 'Antarctica/Casey',
            self::TMZ_220_ANTARCTICA_DAVIS => 'Antarctica/Davis',
            self::TMZ_221_ANTARCTICA_DUMONTDURVILLE => 'Antarctica/DumontDUrville',
            self::TMZ_222_ANTARCTICA_MACQUARIE => 'Antarctica/Macquarie',
            self::TMZ_223_ANTARCTICA_MAWSON => 'Antarctica/Mawson',
            self::TMZ_224_ANTARCTICA_MCMURDO => 'Antarctica/McMurdo',
            self::TMZ_225_ANTARCTICA_PALMER => 'Antarctica/Palmer',
            self::TMZ_226_ANTARCTICA_ROTHERA => 'Antarctica/Rothera',
            self::TMZ_227_ANTARCTICA_SOUTH_POLE => 'Antarctica/South_Pole',
            self::TMZ_228_ANTARCTICA_SYOWA => 'Antarctica/Syowa',
            self::TMZ_229_ANTARCTICA_TROLL => 'Antarctica/Troll',
            self::TMZ_230_ANTARCTICA_VOSTOK => 'Antarctica/Vostok',
            self::TMZ_231_ARCTIC_LONGYEARBYEN => 'Arctic/Longyearbyen',
            self::TMZ_232_ASIA_ADEN => 'Asia/Aden',
            self::TMZ_233_ASIA_ALMATY => 'Asia/Almaty',
            self::TMZ_234_ASIA_AMMAN => 'Asia/Amman',
            self::TMZ_235_ASIA_ANADYR => 'Asia/Anadyr',
            self::TMZ_236_ASIA_AQTAU => 'Asia/Aqtau',
            self::TMZ_237_ASIA_AQTOBE => 'Asia/Aqtobe',
            self::TMZ_238_ASIA_ASHGABAT => 'Asia/Ashgabat',
            self::TMZ_239_ASIA_ASHKHABAD => 'Asia/Ashkhabad',
            self::TMZ_240_ASIA_BAGHDAD => 'Asia/Baghdad',
            self::TMZ_241_ASIA_BAHRAIN => 'Asia/Bahrain',
            self::TMZ_242_ASIA_BAKU => 'Asia/Baku',
            self::TMZ_243_ASIA_BANGKOK => 'Asia/Bangkok',
            self::TMZ_244_ASIA_BEIRUT => 'Asia/Beirut',
            self::TMZ_245_ASIA_BISHKEK => 'Asia/Bishkek',
            self::TMZ_246_ASIA_BRUNEI => 'Asia/Brunei',
            self::TMZ_247_ASIA_CALCUTTA => 'Asia/Calcutta',
            self::TMZ_248_ASIA_CHITA => 'Asia/Chita',
            self::TMZ_249_ASIA_CHOIBALSAN => 'Asia/Choibalsan',
            self::TMZ_250_ASIA_CHONGQING => 'Asia/Chongqing',
            self::TMZ_251_ASIA_CHUNGKING => 'Asia/Chungking',
            self::TMZ_252_ASIA_COLOMBO => 'Asia/Colombo',
            self::TMZ_253_ASIA_DACCA => 'Asia/Dacca',
            self::TMZ_254_ASIA_DAMASCUS => 'Asia/Damascus',
            self::TMZ_255_ASIA_DHAKA => 'Asia/Dhaka',
            self::TMZ_256_ASIA_DILI => 'Asia/Dili',
            self::TMZ_257_ASIA_DUBAI => 'Asia/Dubai',
            self::TMZ_258_ASIA_DUSHANBE => 'Asia/Dushanbe',
            self::TMZ_259_ASIA_GAZA => 'Asia/Gaza',
            self::TMZ_260_ASIA_HARBIN => 'Asia/Harbin',
            self::TMZ_261_ASIA_HEBRON => 'Asia/Hebron',
            self::TMZ_262_ASIA_HO_CHI_MINH => 'Asia/Ho_Chi_Minh',
            self::TMZ_263_ASIA_HONG_KONG => 'Asia/Hong_Kong',
            self::TMZ_264_ASIA_HOVD => 'Asia/Hovd',
            self::TMZ_265_ASIA_IRKUTSK => 'Asia/Irkutsk',
            self::TMZ_266_ASIA_ISTANBUL => 'Asia/Istanbul',
            self::TMZ_267_ASIA_JAKARTA => 'Asia/Jakarta',
            self::TMZ_268_ASIA_JAYAPURA => 'Asia/Jayapura',
            self::TMZ_269_ASIA_JERUSALEM => 'Asia/Jerusalem',
            self::TMZ_270_ASIA_KABUL => 'Asia/Kabul',
            self::TMZ_271_ASIA_KAMCHATKA => 'Asia/Kamchatka',
            self::TMZ_272_ASIA_KARACHI => 'Asia/Karachi',
            self::TMZ_273_ASIA_KASHGAR => 'Asia/Kashgar',
            self::TMZ_274_ASIA_KATHMANDU => 'Asia/Kathmandu',
            self::TMZ_275_ASIA_KATMANDU => 'Asia/Katmandu',
            self::TMZ_276_ASIA_KHANDYGA => 'Asia/Khandyga',
            self::TMZ_277_ASIA_KOLKATA => 'Asia/Kolkata',
            self::TMZ_278_ASIA_KRASNOYARSK => 'Asia/Krasnoyarsk',
            self::TMZ_279_ASIA_KUALA_LUMPUR => 'Asia/Kuala_Lumpur',
            self::TMZ_280_ASIA_KUCHING => 'Asia/Kuching',
            self::TMZ_281_ASIA_KUWAIT => 'Asia/Kuwait',
            self::TMZ_282_ASIA_MACAO => 'Asia/Macao',
            self::TMZ_283_ASIA_MACAU => 'Asia/Macau',
            self::TMZ_284_ASIA_MAGADAN => 'Asia/Magadan',
            self::TMZ_285_ASIA_MAKASSAR => 'Asia/Makassar',
            self::TMZ_286_ASIA_MANILA => 'Asia/Manila',
            self::TMZ_287_ASIA_MUSCAT => 'Asia/Muscat',
            self::TMZ_288_ASIA_NICOSIA => 'Asia/Nicosia',
            self::TMZ_289_ASIA_NOVOKUZNETSK => 'Asia/Novokuznetsk',
            self::TMZ_290_ASIA_NOVOSIBIRSK => 'Asia/Novosibirsk',
            self::TMZ_291_ASIA_OMSK => 'Asia/Omsk',
            self::TMZ_292_ASIA_ORAL => 'Asia/Oral',
            self::TMZ_293_ASIA_PHNOM_PENH => 'Asia/Phnom_Penh',
            self::TMZ_294_ASIA_PONTIANAK => 'Asia/Pontianak',
            self::TMZ_295_ASIA_PYONGYANG => 'Asia/Pyongyang',
            self::TMZ_296_ASIA_QATAR => 'Asia/Qatar',
            self::TMZ_297_ASIA_QYZYLORDA => 'Asia/Qyzylorda',
            self::TMZ_298_ASIA_RANGOON => 'Asia/Rangoon',
            self::TMZ_299_ASIA_RIYADH => 'Asia/Riyadh',
            self::TMZ_300_ASIA_SAIGON => 'Asia/Saigon',
            self::TMZ_301_ASIA_SAKHALIN => 'Asia/Sakhalin',
            self::TMZ_302_ASIA_SAMARKAND => 'Asia/Samarkand',
            self::TMZ_303_ASIA_SEOUL => 'Asia/Seoul',
            self::TMZ_304_ASIA_SHANGHAI => 'Asia/Shanghai',
            self::TMZ_305_ASIA_SINGAPORE => 'Asia/Singapore',
            self::TMZ_306_ASIA_SREDNEKOLYMSK => 'Asia/Srednekolymsk',
            self::TMZ_307_ASIA_TAIPEI => 'Asia/Taipei',
            self::TMZ_308_ASIA_TASHKENT => 'Asia/Tashkent',
            self::TMZ_309_ASIA_TBILISI => 'Asia/Tbilisi',
            self::TMZ_310_ASIA_TEHRAN => 'Asia/Tehran',
            self::TMZ_311_ASIA_TEL_AVIV => 'Asia/Tel_Aviv',
            self::TMZ_312_ASIA_THIMBU => 'Asia/Thimbu',
            self::TMZ_313_ASIA_THIMPHU => 'Asia/Thimphu',
            self::TMZ_314_ASIA_TOKYO => 'Asia/Tokyo',
            self::TMZ_315_ASIA_UJUNG_PANDANG => 'Asia/Ujung_Pandang',
            self::TMZ_316_ASIA_ULAANBAATAR => 'Asia/Ulaanbaatar',
            self::TMZ_317_ASIA_ULAN_BATOR => 'Asia/Ulan_Bator',
            self::TMZ_318_ASIA_URUMQI => 'Asia/Urumqi',
            self::TMZ_319_ASIA_UST_NERA => 'Asia/Ust-Nera',
            self::TMZ_320_ASIA_VIENTIANE => 'Asia/Vientiane',
            self::TMZ_321_ASIA_VLADIVOSTOK => 'Asia/Vladivostok',
            self::TMZ_322_ASIA_YAKUTSK => 'Asia/Yakutsk',
            self::TMZ_323_ASIA_YEKATERINBURG => 'Asia/Yekaterinburg',
            self::TMZ_324_ASIA_YEREVAN => 'Asia/Yerevan',
            self::TMZ_325_ATLANTIC_AZORES => 'Atlantic/Azores',
            self::TMZ_326_ATLANTIC_BERMUDA => 'Atlantic/Bermuda',
            self::TMZ_327_ATLANTIC_CANARY => 'Atlantic/Canary',
            self::TMZ_328_ATLANTIC_CAPE_VERDE => 'Atlantic/Cape_Verde',
            self::TMZ_329_ATLANTIC_FAEROE => 'Atlantic/Faeroe',
            self::TMZ_330_ATLANTIC_FAROE => 'Atlantic/Faroe',
            self::TMZ_331_ATLANTIC_JAN_MAYEN => 'Atlantic/Jan_Mayen',
            self::TMZ_332_ATLANTIC_MADEIRA => 'Atlantic/Madeira',
            self::TMZ_333_ATLANTIC_REYKJAVIK => 'Atlantic/Reykjavik',
            self::TMZ_334_ATLANTIC_SOUTH_GEORGIA => 'Atlantic/South_Georgia',
            self::TMZ_335_ATLANTIC_ST_HELENA => 'Atlantic/St_Helena',
            self::TMZ_336_ATLANTIC_STANLEY => 'Atlantic/Stanley',
            self::TMZ_337_AUSTRALIA_ACT => 'Australia/ACT',
            self::TMZ_338_AUSTRALIA_ADELAIDE => 'Australia/Adelaide',
            self::TMZ_339_AUSTRALIA_BRISBANE => 'Australia/Brisbane',
            self::TMZ_340_AUSTRALIA_BROKEN_HILL => 'Australia/Broken_Hill',
            self::TMZ_341_AUSTRALIA_CANBERRA => 'Australia/Canberra',
            self::TMZ_342_AUSTRALIA_CURRIE => 'Australia/Currie',
            self::TMZ_343_AUSTRALIA_DARWIN => 'Australia/Darwin',
            self::TMZ_344_AUSTRALIA_EUCLA => 'Australia/Eucla',
            self::TMZ_345_AUSTRALIA_HOBART => 'Australia/Hobart',
            self::TMZ_346_AUSTRALIA_LHI => 'Australia/LHI',
            self::TMZ_347_AUSTRALIA_LINDEMAN => 'Australia/Lindeman',
            self::TMZ_348_AUSTRALIA_LORD_HOWE => 'Australia/Lord_Howe',
            self::TMZ_349_AUSTRALIA_MELBOURNE => 'Australia/Melbourne',
            self::TMZ_350_AUSTRALIA_NSW => 'Australia/NSW',
            self::TMZ_351_AUSTRALIA_NORTH => 'Australia/North',
            self::TMZ_352_AUSTRALIA_PERTH => 'Australia/Perth',
            self::TMZ_353_AUSTRALIA_QUEENSLAND => 'Australia/Queensland',
            self::TMZ_354_AUSTRALIA_SOUTH => 'Australia/South',
            self::TMZ_355_AUSTRALIA_SYDNEY => 'Australia/Sydney',
            self::TMZ_356_AUSTRALIA_TASMANIA => 'Australia/Tasmania',
            self::TMZ_357_AUSTRALIA_VICTORIA => 'Australia/Victoria',
            self::TMZ_358_AUSTRALIA_WEST => 'Australia/West',
            self::TMZ_359_AUSTRALIA_YANCOWINNA => 'Australia/Yancowinna',
            self::TMZ_360_BRAZIL_ACRE => 'Brazil/Acre',
            self::TMZ_361_BRAZIL_DENORONHA => 'Brazil/DeNoronha',
            self::TMZ_362_BRAZIL_EAST => 'Brazil/East',
            self::TMZ_363_BRAZIL_WEST => 'Brazil/West',
            self::TMZ_364_CET => 'CET',
            self::TMZ_365_CST6CDT => 'CST6CDT',
            self::TMZ_366_CANADA_ATLANTIC => 'Canada/Atlantic',
            self::TMZ_367_CANADA_CENTRAL => 'Canada/Central',
            self::TMZ_368_CANADA_EAST_SASKATCHEWAN => 'Canada/East-Saskatchewan',
            self::TMZ_369_CANADA_EASTERN => 'Canada/Eastern',
            self::TMZ_370_CANADA_MOUNTAIN => 'Canada/Mountain',
            self::TMZ_371_CANADA_NEWFOUNDLAND => 'Canada/Newfoundland',
            self::TMZ_372_CANADA_PACIFIC => 'Canada/Pacific',
            self::TMZ_373_CANADA_SASKATCHEWAN => 'Canada/Saskatchewan',
            self::TMZ_374_CANADA_YUKON => 'Canada/Yukon',
            self::TMZ_375_CHILE_CONTINENTAL => 'Chile/Continental',
            self::TMZ_376_CHILE_EASTERISLAND => 'Chile/EasterIsland',
            self::TMZ_377_CUBA => 'Cuba',
            self::TMZ_378_EET => 'EET',
            self::TMZ_379_EST => 'EST',
            self::TMZ_380_EST5EDT => 'EST5EDT',
            self::TMZ_381_EGYPT => 'Egypt',
            self::TMZ_382_EIRE => 'Eire',
            self::TMZ_383_ETC_GMT => 'Etc/GMT',
            self::TMZ_384_ETC_GMT_0 => 'Etc/GMT+0',
            self::TMZ_385_ETC_GMT_1 => 'Etc/GMT+1',
            self::TMZ_386_ETC_GMT_10 => 'Etc/GMT+10',
            self::TMZ_387_ETC_GMT_11 => 'Etc/GMT+11',
            self::TMZ_388_ETC_GMT_12 => 'Etc/GMT+12',
            self::TMZ_389_ETC_GMT_2 => 'Etc/GMT+2',
            self::TMZ_390_ETC_GMT_3 => 'Etc/GMT+3',
            self::TMZ_391_ETC_GMT_4 => 'Etc/GMT+4',
            self::TMZ_392_ETC_GMT_5 => 'Etc/GMT+5',
            self::TMZ_393_ETC_GMT_6 => 'Etc/GMT+6',
            self::TMZ_394_ETC_GMT_7 => 'Etc/GMT+7',
            self::TMZ_395_ETC_GMT_8 => 'Etc/GMT+8',
            self::TMZ_396_ETC_GMT_9 => 'Etc/GMT+9',
            self::TMZ_397_ETC_GMT_0 => 'Etc/GMT-0',
            self::TMZ_398_ETC_GMT_1 => 'Etc/GMT-1',
            self::TMZ_399_ETC_GMT_10 => 'Etc/GMT-10',
            self::TMZ_400_ETC_GMT_11 => 'Etc/GMT-11',
            self::TMZ_401_ETC_GMT_12 => 'Etc/GMT-12',
            self::TMZ_402_ETC_GMT_13 => 'Etc/GMT-13',
            self::TMZ_403_ETC_GMT_14 => 'Etc/GMT-14',
            self::TMZ_404_ETC_GMT_2 => 'Etc/GMT-2',
            self::TMZ_405_ETC_GMT_3 => 'Etc/GMT-3',
            self::TMZ_406_ETC_GMT_4 => 'Etc/GMT-4',
            self::TMZ_407_ETC_GMT_5 => 'Etc/GMT-5',
            self::TMZ_408_ETC_GMT_6 => 'Etc/GMT-6',
            self::TMZ_409_ETC_GMT_7 => 'Etc/GMT-7',
            self::TMZ_410_ETC_GMT_8 => 'Etc/GMT-8',
            self::TMZ_411_ETC_GMT_9 => 'Etc/GMT-9',
            self::TMZ_412_ETC_GMT0 => 'Etc/GMT0',
            self::TMZ_413_ETC_GREENWICH => 'Etc/Greenwich',
            self::TMZ_414_ETC_UCT => 'Etc/UCT',
            self::TMZ_415_ETC_UTC => 'Etc/UTC',
            self::TMZ_416_ETC_UNIVERSAL => 'Etc/Universal',
            self::TMZ_417_ETC_ZULU => 'Etc/Zulu',
            self::TMZ_418_EUROPE_AMSTERDAM => 'Europe/Amsterdam',
            self::TMZ_419_EUROPE_ANDORRA => 'Europe/Andorra',
            self::TMZ_420_EUROPE_ATHENS => 'Europe/Athens',
            self::TMZ_421_EUROPE_BELFAST => 'Europe/Belfast',
            self::TMZ_422_EUROPE_BELGRADE => 'Europe/Belgrade',
            self::TMZ_423_EUROPE_BERLIN => 'Europe/Berlin',
            self::TMZ_424_EUROPE_BRATISLAVA => 'Europe/Bratislava',
            self::TMZ_425_EUROPE_BRUSSELS => 'Europe/Brussels',
            self::TMZ_426_EUROPE_BUCHAREST => 'Europe/Bucharest',
            self::TMZ_427_EUROPE_BUDAPEST => 'Europe/Budapest',
            self::TMZ_428_EUROPE_BUSINGEN => 'Europe/Busingen',
            self::TMZ_429_EUROPE_CHISINAU => 'Europe/Chisinau',
            self::TMZ_430_EUROPE_COPENHAGEN => 'Europe/Copenhagen',
            self::TMZ_431_EUROPE_DUBLIN => 'Europe/Dublin',
            self::TMZ_432_EUROPE_GIBRALTAR => 'Europe/Gibraltar',
            self::TMZ_433_EUROPE_GUERNSEY => 'Europe/Guernsey',
            self::TMZ_434_EUROPE_HELSINKI => 'Europe/Helsinki',
            self::TMZ_435_EUROPE_ISLE_OF_MAN => 'Europe/Isle_of_Man',
            self::TMZ_436_EUROPE_ISTANBUL => 'Europe/Istanbul',
            self::TMZ_437_EUROPE_JERSEY => 'Europe/Jersey',
            self::TMZ_438_EUROPE_KALININGRAD => 'Europe/Kaliningrad',
            self::TMZ_439_EUROPE_KIEV => 'Europe/Kiev',
            self::TMZ_440_EUROPE_LISBON => 'Europe/Lisbon',
            self::TMZ_441_EUROPE_LJUBLJANA => 'Europe/Ljubljana',
            self::TMZ_442_EUROPE_LONDON => 'Europe/London',
            self::TMZ_443_EUROPE_LUXEMBOURG => 'Europe/Luxembourg',
            self::TMZ_444_EUROPE_MADRID => 'Europe/Madrid',
            self::TMZ_445_EUROPE_MALTA => 'Europe/Malta',
            self::TMZ_446_EUROPE_MARIEHAMN => 'Europe/Mariehamn',
            self::TMZ_447_EUROPE_MINSK => 'Europe/Minsk',
            self::TMZ_448_EUROPE_MONACO => 'Europe/Monaco',
            self::TMZ_449_EUROPE_MOSCOW => 'Europe/Moscow',
            self::TMZ_450_EUROPE_NICOSIA => 'Europe/Nicosia',
            self::TMZ_451_EUROPE_OSLO => 'Europe/Oslo',
            self::TMZ_452_EUROPE_PARIS => 'Europe/Paris',
            self::TMZ_453_EUROPE_PODGORICA => 'Europe/Podgorica',
            self::TMZ_454_EUROPE_PRAGUE => 'Europe/Prague',
            self::TMZ_455_EUROPE_RIGA => 'Europe/Riga',
            self::TMZ_456_EUROPE_ROME => 'Europe/Rome',
            self::TMZ_457_EUROPE_SAMARA => 'Europe/Samara',
            self::TMZ_458_EUROPE_SAN_MARINO => 'Europe/San_Marino',
            self::TMZ_459_EUROPE_SARAJEVO => 'Europe/Sarajevo',
            self::TMZ_460_EUROPE_SIMFEROPOL => 'Europe/Simferopol',
            self::TMZ_461_EUROPE_SKOPJE => 'Europe/Skopje',
            self::TMZ_462_EUROPE_SOFIA => 'Europe/Sofia',
            self::TMZ_463_EUROPE_STOCKHOLM => 'Europe/Stockholm',
            self::TMZ_464_EUROPE_TALLINN => 'Europe/Tallinn',
            self::TMZ_465_EUROPE_TIRANE => 'Europe/Tirane',
            self::TMZ_466_EUROPE_TIRASPOL => 'Europe/Tiraspol',
            self::TMZ_467_EUROPE_UZHGOROD => 'Europe/Uzhgorod',
            self::TMZ_468_EUROPE_VADUZ => 'Europe/Vaduz',
            self::TMZ_469_EUROPE_VATICAN => 'Europe/Vatican',
            self::TMZ_470_EUROPE_VIENNA => 'Europe/Vienna',
            self::TMZ_471_EUROPE_VILNIUS => 'Europe/Vilnius',
            self::TMZ_472_EUROPE_VOLGOGRAD => 'Europe/Volgograd',
            self::TMZ_473_EUROPE_WARSAW => 'Europe/Warsaw',
            self::TMZ_474_EUROPE_ZAGREB => 'Europe/Zagreb',
            self::TMZ_475_EUROPE_ZAPOROZHYE => 'Europe/Zaporozhye',
            self::TMZ_476_EUROPE_ZURICH => 'Europe/Zurich',
            self::TMZ_477_FACTORY => 'Factory',
            self::TMZ_478_GB => 'GB',
            self::TMZ_479_GB_EIRE => 'GB-Eire',
            self::TMZ_480_GMT => 'GMT',
            self::TMZ_481_GMT_0 => 'GMT+0',
            self::TMZ_482_GMT_0 => 'GMT-0',
            self::TMZ_483_GMT0 => 'GMT0',
            self::TMZ_484_GREENWICH => 'Greenwich',
            self::TMZ_485_HST => 'HST',
            self::TMZ_486_HONGKONG => 'Hongkong',
            self::TMZ_487_ICELAND => 'Iceland',
            self::TMZ_488_INDIAN_ANTANANARIVO => 'Indian/Antananarivo',
            self::TMZ_489_INDIAN_CHAGOS => 'Indian/Chagos',
            self::TMZ_490_INDIAN_CHRISTMAS => 'Indian/Christmas',
            self::TMZ_491_INDIAN_COCOS => 'Indian/Cocos',
            self::TMZ_492_INDIAN_COMORO => 'Indian/Comoro',
            self::TMZ_493_INDIAN_KERGUELEN => 'Indian/Kerguelen',
            self::TMZ_494_INDIAN_MAHE => 'Indian/Mahe',
            self::TMZ_495_INDIAN_MALDIVES => 'Indian/Maldives',
            self::TMZ_496_INDIAN_MAURITIUS => 'Indian/Mauritius',
            self::TMZ_497_INDIAN_MAYOTTE => 'Indian/Mayotte',
            self::TMZ_498_INDIAN_REUNION => 'Indian/Reunion',
            self::TMZ_499_IRAN => 'Iran',
            self::TMZ_500_ISRAEL => 'Israel',
            self::TMZ_501_JAMAICA => 'Jamaica',
            self::TMZ_502_JAPAN => 'Japan',
            self::TMZ_503_KWAJALEIN => 'Kwajalein',
            self::TMZ_504_LIBYA => 'Libya',
            self::TMZ_505_MET => 'MET',
            self::TMZ_506_MST => 'MST',
            self::TMZ_507_MST7MDT => 'MST7MDT',
            self::TMZ_508_MEXICO_BAJANORTE => 'Mexico/BajaNorte',
            self::TMZ_509_MEXICO_BAJASUR => 'Mexico/BajaSur',
            self::TMZ_510_MEXICO_GENERAL => 'Mexico/General',
            self::TMZ_511_NZ => 'NZ',
            self::TMZ_512_NZ_CHAT => 'NZ-CHAT',
            self::TMZ_513_NAVAJO => 'Navajo',
            self::TMZ_514_PRC => 'PRC',
            self::TMZ_515_PST8PDT => 'PST8PDT',
            self::TMZ_516_PACIFIC_APIA => 'Pacific/Apia',
            self::TMZ_517_PACIFIC_AUCKLAND => 'Pacific/Auckland',
            self::TMZ_518_PACIFIC_BOUGAINVILLE => 'Pacific/Bougainville',
            self::TMZ_519_PACIFIC_CHATHAM => 'Pacific/Chatham',
            self::TMZ_520_PACIFIC_CHUUK => 'Pacific/Chuuk',
            self::TMZ_521_PACIFIC_EASTER => 'Pacific/Easter',
            self::TMZ_522_PACIFIC_EFATE => 'Pacific/Efate',
            self::TMZ_523_PACIFIC_ENDERBURY => 'Pacific/Enderbury',
            self::TMZ_524_PACIFIC_FAKAOFO => 'Pacific/Fakaofo',
            self::TMZ_525_PACIFIC_FIJI => 'Pacific/Fiji',
            self::TMZ_526_PACIFIC_FUNAFUTI => 'Pacific/Funafuti',
            self::TMZ_527_PACIFIC_GALAPAGOS => 'Pacific/Galapagos',
            self::TMZ_528_PACIFIC_GAMBIER => 'Pacific/Gambier',
            self::TMZ_529_PACIFIC_GUADALCANAL => 'Pacific/Guadalcanal',
            self::TMZ_530_PACIFIC_GUAM => 'Pacific/Guam',
            self::TMZ_531_PACIFIC_HONOLULU => 'Pacific/Honolulu',
            self::TMZ_532_PACIFIC_JOHNSTON => 'Pacific/Johnston',
            self::TMZ_533_PACIFIC_KIRITIMATI => 'Pacific/Kiritimati',
            self::TMZ_534_PACIFIC_KOSRAE => 'Pacific/Kosrae',
            self::TMZ_535_PACIFIC_KWAJALEIN => 'Pacific/Kwajalein',
            self::TMZ_536_PACIFIC_MAJURO => 'Pacific/Majuro',
            self::TMZ_537_PACIFIC_MARQUESAS => 'Pacific/Marquesas',
            self::TMZ_538_PACIFIC_MIDWAY => 'Pacific/Midway',
            self::TMZ_539_PACIFIC_NAURU => 'Pacific/Nauru',
            self::TMZ_540_PACIFIC_NIUE => 'Pacific/Niue',
            self::TMZ_541_PACIFIC_NORFOLK => 'Pacific/Norfolk',
            self::TMZ_542_PACIFIC_NOUMEA => 'Pacific/Noumea',
            self::TMZ_543_PACIFIC_PAGO_PAGO => 'Pacific/Pago_Pago',
            self::TMZ_544_PACIFIC_PALAU => 'Pacific/Palau',
            self::TMZ_545_PACIFIC_PITCAIRN => 'Pacific/Pitcairn',
            self::TMZ_546_PACIFIC_POHNPEI => 'Pacific/Pohnpei',
            self::TMZ_547_PACIFIC_PONAPE => 'Pacific/Ponape',
            self::TMZ_548_PACIFIC_PORT_MORESBY => 'Pacific/Port_Moresby',
            self::TMZ_549_PACIFIC_RAROTONGA => 'Pacific/Rarotonga',
            self::TMZ_550_PACIFIC_SAIPAN => 'Pacific/Saipan',
            self::TMZ_551_PACIFIC_SAMOA => 'Pacific/Samoa',
            self::TMZ_552_PACIFIC_TAHITI => 'Pacific/Tahiti',
            self::TMZ_553_PACIFIC_TARAWA => 'Pacific/Tarawa',
            self::TMZ_554_PACIFIC_TONGATAPU => 'Pacific/Tongatapu',
            self::TMZ_555_PACIFIC_TRUK => 'Pacific/Truk',
            self::TMZ_556_PACIFIC_WAKE => 'Pacific/Wake',
            self::TMZ_557_PACIFIC_WALLIS => 'Pacific/Wallis',
            self::TMZ_558_PACIFIC_YAP => 'Pacific/Yap',
            self::TMZ_559_POLAND => 'Poland',
            self::TMZ_560_PORTUGAL => 'Portugal',
            self::TMZ_561_ROC => 'ROC',
            self::TMZ_562_ROK => 'ROK',
            self::TMZ_563_SINGAPORE => 'Singapore',
            self::TMZ_564_TURKEY => 'Turkey',
            self::TMZ_565_US_ALASKA => 'US/Alaska',
            self::TMZ_566_US_ALEUTIAN => 'US/Aleutian',
            self::TMZ_567_US_ARIZONA => 'US/Arizona',
            self::TMZ_568_US_CENTRAL => 'US/Central',
            self::TMZ_569_US_EAST_INDIANA => 'US/East-Indiana',
            self::TMZ_570_US_EASTERN => 'US/Eastern',
            self::TMZ_571_US_HAWAII => 'US/Hawaii',
            self::TMZ_572_US_INDIANA_STARKE => 'US/Indiana-Starke',
            self::TMZ_573_US_MICHIGAN => 'US/Michigan',
            self::TMZ_574_US_MOUNTAIN => 'US/Mountain',
            self::TMZ_575_US_PACIFIC => 'US/Pacific',
            self::TMZ_576_US_PACIFIC_NEW => 'US/Pacific-New',
            self::TMZ_577_US_SAMOA => 'US/Samoa',
            self::TMZ_578_UTC => 'UTC',
            self::TMZ_579_UNIVERSAL => 'Universal',
            self::TMZ_580_W_SU => 'W-SU',
            self::TMZ_581_WET => 'WET',
            self::TMZ_582_ZULU => 'Zulu',
            default => 'UTC'
        };
    }

    public function default(): static
    {
        return self::TMZ_578_UTC;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value(): int
    {
        return $this->value;
    }

    public function names(): array
    {
        $assoc = [];
        $list = self::cases();
        array_walk($list, function ($case) use (&$assoc) {
            $assoc[$case->value] = $case->name;
        });
        return $assoc;
    }

    public function values(): array
    {
        $assoc = [];
        $list = self::cases();
        array_walk($list, function ($case) use (&$assoc) {
            $assoc[$case->name] = $case->value;
        });
        return $assoc;
    }

    public static function enum(int|string|null $value): static|null
    {
        $list = self::cases();
        $enums = array_filter($list, function ($case) use ($value) {
            if (is_numeric($value) && ($case->value == $value)) {
                return true;
            }
            if (is_string($value) && ($case->name == $value)) {
                return true;
            }
            if (strtolower(preg_replace("/[^0-9a-zA-Z\+\-]/", "", $value)) == strtolower(preg_replace("/[^0-9a-zA-Z\+\-]/", "", $case->timezone()))) {
                return true;
            }
            return false;
        });
        return current($enums) ?: null;
    }

    public static function options(): array
    {
        $assoc = [];
        $list = self::cases();
        array_walk($list, function ($case) use (&$assoc) {
            $assoc[] = ['id' => $case->value, 'description' => $case->label];
        });
        return $assoc;
    }

    public static function assoc(): array
    {
        $assoc = [];
        $list = self::cases();
        array_walk($list, function ($case) use (&$assoc) {
            $assoc[$case->value] = $case->label();
        });
        return $assoc;
    }
}
