version: '3'
networks:
  skedway-network:
volumes:
  skedway-database-mysql:
services:
#serviço database mysql
  database:
    build:
      context: "./docker"
      dockerfile: 4-Mysql.Dockerfile
    container_name: mysql-skedway
    privileged: true
    restart: always
    networks:
      - skedway-network
    env_file:
        - ./.env
    ports:
      - "3306:3306"
    volumes:
      - skedway-database-mysql:/var/lib/mysql
      - ./database/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
#serviço nginx
  nginx:
    build:
      context: "./docker"
      dockerfile: 1-Nginx.Dockerfile
    container_name: nginx-skedway
    privileged: true
    restart: always
    networks:
      - skedway-network
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - "./:/app/skedway/"
      - "./nginx/settings/:/etc/nginx/conf.d/"
      - "./nginx/certificate/:/etc/nginx/ssl/"
      - "./nginx/settings/nginx.conf:/etc/nginx/nginx.conf"
#serviço php-8.2
  php:
    build:
      context: "./docker"
      dockerfile: 2-Php.Dockerfile
    container_name: php-skedway
    privileged: true
    restart: 'always'
    networks:
      - skedway-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - "./:/app/skedway/"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
#serviço php composer
  composer:
    build:
      context: "./docker"
      dockerfile: 3-Composer.Dockerfile
    container_name: php-composer-skedway
    privileged: true
    restart: 'no'
    networks:
      - skedway-network
    environment:
      - COMPOSER_CACHE_DIR=/etc/cache/composer
    volumes:
      - "./:/app/"
    command: ['install']

